export const { default: IconCategory } = require('./Categories');
export const { default: IconCustomer } = require('./Customers');
export const { default: IconOrder } = require('./Orders');
export const { default: IconProduct } = require('./Products');
export { default as IconEdit } from './IconEdit';
export { default as IconDelete } from './IconDelete';
export { default as IconFilter } from './IconFilter';
export { default as IconAdd } from './IconAdd';
export { default as IconArrowOutline } from './IconArrowOutline';
